kind: pipeline
name: default

steps:
- name: frontend
  image: quay.io/quarkus/ubi-quarkus-native-image:19.2.1
  user: root
  commands:
  - whoami
  - pwd
  - ls -lrta
  - unset MAVEN_CONFIG
  - ./mvnw -Pnative package 
- name: docker  
  image: plugins/docker
  settings:
    repo: toaler/quarkus-sandbox
    dockerfile: Dockerfile.native
    tags:
     - '0.1'
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
