kind: pipeline
name: default

steps:
- name: frontend
  image: quay.io/quarkus/centos-quarkus-maven:19.2.1
  commands:
  - ls -lrt
  - pwd
  - chown -R quarkus .
  - ls -lrt
  - su - quarkus
  - whoami
  - unset MAVEN_CONFIG
  - ./mvnw -Pnative package 
- name: docker  
  image: plugins/docker
  settings:
    repo: toaler/quarkus-sandbox
    tags:
     - '0.1'
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
