kind: pipeline
name: default

workspace:
  base: /home/
  path: quarkus

steps:
- name: frontend
  image: quay.io/quarkus/centos-quarkus-maven:19.2.1
  commands:
  - whoami
  - pwd
  - mkdir ~/.m2
  - ls -lrta
  - unset MAVEN_CONFIG
  - ./mvnw -Pnative package 
  - ls -lrt /home/quarkus/src/target
- name: docker  
  image: plugins/docker
  settings:
    repo: toaler/quarkus-sandbox
    dockerfile: Dockerfile.native
    tags:
     - '0.1'
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
