kind: pipeline
name: default

steps:
- name: frontend
  image: adoptopenjdk/maven-openjdk11
  commands:
  - ./mvnw package 
- name: docker  
  image: plugins/docker
  settings:
    repo: toaler/quarkus-sandbox
    tags:
     - '0.1'
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
