FROM registry.access.redhat.com/ubi8/ubi-minimal
COPY target/getting-started-1.0-SNAPSHOT-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
