FROM registry.access.redhat.com/ubi8/ubi-minimal
RUN ls -lrt /
RUN find / -name target
WORKDIR /work/
COPY /home/quarkus/src/target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
